const BACKGROUND_COLOR_PREFIX = 'chayns__background-color';

// main BACKGROUND_COLOR palettes
export const BACKGROUND_COLOR_000 = `${BACKGROUND_COLOR_PREFIX}--000`;
export const BACKGROUND_COLOR_001 = `${BACKGROUND_COLOR_PREFIX}--001`;
export const BACKGROUND_COLOR_002 = `${BACKGROUND_COLOR_PREFIX}--002`;
export const BACKGROUND_COLOR_003 = `${BACKGROUND_COLOR_PREFIX}--003`;
export const BACKGROUND_COLOR_004 = `${BACKGROUND_COLOR_PREFIX}--004`;
export const BACKGROUND_COLOR_005 = `${BACKGROUND_COLOR_PREFIX}--005`;
export const BACKGROUND_COLOR_006 = `${BACKGROUND_COLOR_PREFIX}--006`;
export const BACKGROUND_COLOR_007 = `${BACKGROUND_COLOR_PREFIX}--007`;
export const BACKGROUND_COLOR_008 = `${BACKGROUND_COLOR_PREFIX}--008`;
export const BACKGROUND_COLOR_009 = `${BACKGROUND_COLOR_PREFIX}--009`;

export const BACKGROUND_COLOR_100 = `${BACKGROUND_COLOR_PREFIX}--100`;
export const BACKGROUND_COLOR_101 = `${BACKGROUND_COLOR_PREFIX}--101`;
export const BACKGROUND_COLOR_102 = `${BACKGROUND_COLOR_PREFIX}--102`;
export const BACKGROUND_COLOR_103 = `${BACKGROUND_COLOR_PREFIX}--103`;
export const BACKGROUND_COLOR_104 = `${BACKGROUND_COLOR_PREFIX}--104`;
export const BACKGROUND_COLOR_105 = `${BACKGROUND_COLOR_PREFIX}--105`;
export const BACKGROUND_COLOR_106 = `${BACKGROUND_COLOR_PREFIX}--106`;
export const BACKGROUND_COLOR_107 = `${BACKGROUND_COLOR_PREFIX}--107`;
export const BACKGROUND_COLOR_108 = `${BACKGROUND_COLOR_PREFIX}--108`;
export const BACKGROUND_COLOR_109 = `${BACKGROUND_COLOR_PREFIX}--109`;

export const BACKGROUND_COLOR_200 = `${BACKGROUND_COLOR_PREFIX}--200`;
export const BACKGROUND_COLOR_201 = `${BACKGROUND_COLOR_PREFIX}--201`;
export const BACKGROUND_COLOR_202 = `${BACKGROUND_COLOR_PREFIX}--202`;
export const BACKGROUND_COLOR_203 = `${BACKGROUND_COLOR_PREFIX}--203`;
export const BACKGROUND_COLOR_204 = `${BACKGROUND_COLOR_PREFIX}--204`;
export const BACKGROUND_COLOR_205 = `${BACKGROUND_COLOR_PREFIX}--205`;
export const BACKGROUND_COLOR_206 = `${BACKGROUND_COLOR_PREFIX}--206`;
export const BACKGROUND_COLOR_207 = `${BACKGROUND_COLOR_PREFIX}--207`;
export const BACKGROUND_COLOR_208 = `${BACKGROUND_COLOR_PREFIX}--208`;
export const BACKGROUND_COLOR_209 = `${BACKGROUND_COLOR_PREFIX}--209`;

export const BACKGROUND_COLOR_300 = `${BACKGROUND_COLOR_PREFIX}--300`;
export const BACKGROUND_COLOR_301 = `${BACKGROUND_COLOR_PREFIX}--301`;
export const BACKGROUND_COLOR_302 = `${BACKGROUND_COLOR_PREFIX}--302`;
export const BACKGROUND_COLOR_303 = `${BACKGROUND_COLOR_PREFIX}--303`;
export const BACKGROUND_COLOR_304 = `${BACKGROUND_COLOR_PREFIX}--304`;
export const BACKGROUND_COLOR_305 = `${BACKGROUND_COLOR_PREFIX}--305`;
export const BACKGROUND_COLOR_306 = `${BACKGROUND_COLOR_PREFIX}--306`;
export const BACKGROUND_COLOR_307 = `${BACKGROUND_COLOR_PREFIX}--307`;
export const BACKGROUND_COLOR_308 = `${BACKGROUND_COLOR_PREFIX}--308`;
export const BACKGROUND_COLOR_309 = `${BACKGROUND_COLOR_PREFIX}--309`;

export const BACKGROUND_COLOR_PRIMARY = `${BACKGROUND_COLOR_PREFIX}--primary`;
export const BACKGROUND_COLOR_HEADLINE = `${BACKGROUND_COLOR_PREFIX}--headline`;
export const BACKGROUND_COLOR_TEXT = `${BACKGROUND_COLOR_PREFIX}--text`;
export const BACKGROUND_COLOR_HEADER_BAR = `${BACKGROUND_COLOR_PREFIX}--header-bar`;
export const BACKGROUND_COLOR_CW_BACKGROUND = `${BACKGROUND_COLOR_PREFIX}--cw-background`;

// special BACKGROUND_COLOR palettes
export const BACKGROUND_COLOR_YELLOW_1 = `${BACKGROUND_COLOR_PREFIX}--yellow-1`;
export const BACKGROUND_COLOR_YELLOW_2 = `${BACKGROUND_COLOR_PREFIX}--yellow-2`;
export const BACKGROUND_COLOR_YELLOW_3 = `${BACKGROUND_COLOR_PREFIX}--yellow-3`;
export const BACKGROUND_COLOR_YELLOW_4 = `${BACKGROUND_COLOR_PREFIX}--yellow-4`;

export const BACKGROUND_COLOR_RED_1 = `${BACKGROUND_COLOR_PREFIX}--red-1`;
export const BACKGROUND_COLOR_RED_2 = `${BACKGROUND_COLOR_PREFIX}--red-2`;
export const BACKGROUND_COLOR_RED_3 = `${BACKGROUND_COLOR_PREFIX}--red-3`;
export const BACKGROUND_COLOR_RED_4 = `${BACKGROUND_COLOR_PREFIX}--red-4`;

export const BACKGROUND_COLOR_GREEN_1 = `${BACKGROUND_COLOR_PREFIX}--green-1`;
export const BACKGROUND_COLOR_GREEN_2 = `${BACKGROUND_COLOR_PREFIX}--green-2`;
export const BACKGROUND_COLOR_GREEN_3 = `${BACKGROUND_COLOR_PREFIX}--green-3`;
export const BACKGROUND_COLOR_GREEN_4 = `${BACKGROUND_COLOR_PREFIX}--green-4`;
