const text = {
    de: {
        RELATIVE_TEXT: {
            past: {
                second: 'Gerade eben',
                seconds: 'Gerade eben',
                seconds0: 'Jetzt',
                minute: 'vor einer Minute',
                minutes: 'vor ##rMINUTES## Minuten',
                minutes0: 'vor weniger als einer Minute',
                hour: 'vor einer Stunde',
                hours: 'vor ##rHOURS## Stunden',
                hours0: 'vor weniger als einer Stunde',
                day: 'Gestern',
                days: 'vor ##rDAYS## Tagen',
                days0: 'Heute',
                month: 'vor einem Monat',
                months: 'vor ##rMONTHS## Monaten',
                months0: 'vor weniger als einem Monat',
                year: 'vor einem Jahr',
                years: 'vor ##rYEARS## Jahren',
                years0: 'vor weniger als einem Jahr',
            },
            now: {
                now: 'Jetzt',
            },
            future: {
                second: 'in wenigen Sekunden',
                seconds: 'in wenigen Sekunden',
                seconds0: 'Jetzt',
                minute: 'in einer Minute',
                minutes: 'in ##rMINUTES## Minuten',
                minutes0: 'in weniger als einer Minute',
                hour: 'in einer Stunde',
                hours: 'in ##rHOURS## Stunden',
                hours0: 'in weniger als einer Stunde',
                day: 'Morgen',
                days: 'in ##rDAYS## Tagen',
                days0: 'Heute',
                month: 'in einem Monat',
                months: 'in ##rMONTHS## Monaten',
                months0: 'in weniger als einem Monat',
                year: 'in einem Jahr',
                years: 'in ##rYEARS## Jahren',
                years0: 'in weniger als einem Jahr',
            },
        },
        ABSOLUTE_TEXT: {
            date: '##aDAYS##.##aMONTH##.##aYEARS##',
            dateMW: '##aDAYS##. ##aMONTHw## ##aYEARS##',
            time: '##aHOURS##:##aMINUTES## Uhr',
            datetime: '##aDAYS##.##aMONTH##.##aYEARS##, ##aHOURS##:##aMINUTES## Uhr',
            datetimeMW: '##aDAYS##. ##aMONTHw## ##aYEARS##, ##aHOURS##:##aMINUTES## Uhr',
            at: 'um',
        },
        INTERVAL: {
            differentDays: '##DATE1##, ##TIME1## - ##DATE2##, ##TIME2##',
            sameDay: '##DATE1##, ##TIME1## - ##TIME2##',
        },
        WEEKDAYS: [
            'Montag',
            'Dienstag',
            'Mittwoch',
            'Donnerstag',
            'Freitag',
            'Samstag',
            'Sonntag',
        ],
        MONTHS: [
            'Januar',
            'Februar',
            'März',
            'April',
            'Mai',
            'Juni',
            'Juli',
            'August',
            'September',
            'Oktober',
            'November',
            'Dezember',
        ],
    },
    en: {
        RELATIVE_TEXT: {
            past: {
                second: 'moments ago',
                seconds: 'moments ago',
                seconds0: 'now',
                minute: 'a Minute ago',
                minutes: '##rMINUTES## minutes ago',
                minutes0: 'less than a minute ago',
                hour: 'an hour ago',
                hours: '##rHOURS## hours ago',
                hours0: 'less than an hour ago',
                day: 'yesterday',
                days: '##rDAYS## days ago',
                days0: 'today',
                month: 'a month ago',
                months: '##rMONTHS## months ago',
                months0: 'less than a month ago',
                year: 'a year ago',
                years: '##rYEARS## years ago',
                years0: 'less than a year ago',
            },
            now: {
                now: 'now',
            },
            future: {
                second: 'in a few seconds',
                seconds: 'in a few seconds',
                seconds0: 'now',
                minute: 'in a minute',
                minutes: 'in ##rMINUTES## Minutes',
                minutes0: 'in less than a Minute',
                hour: 'in an hour',
                hours: 'in ##rHOURS## hours',
                hours0: 'in less than an hour',
                day: 'tomorrow',
                days: 'in ##rDAYS## days',
                days0: 'today',
                month: 'in a month',
                months: 'in ##rMONTHS## months',
                months0: 'in less than a month',
                year: 'in a year',
                years: 'in ##rYEARS## years',
                years0: 'in less than a year',
            },
        },
        ABSOLUTE_TEXT: {
            date: '##aDAYS##/##aMONTH##/##aYEARS##',
            dateMW: '##aDAYS## ##aMONTHw## ##aYEARS##',
            time: '##aHOURS##:##aMINUTES##',
            datetime: '##aDAYS##/##aMONTH##/##aYEARS##, ##aHOURS##:##aMINUTES##',
            datetimeMW: '##aDAYS## ##aMONTHw## ##aYEARS##, ##aHOURS##:##aMINUTES##',
            at: 'at',
        },
        INTERVAL: {
            differentDays: '##DATE1##, ##TIME1## - ##DATE2##, ##TIME2##',
            sameDay: '##DATE1##, ##TIME1## - ##TIME2##',
        },
        WEEKDAYS: [
            'monday',
            'tuesday',
            'wednesday',
            'thursday',
            'friday',
            'saturday',
            'sunday',
        ],
        MONTHS: [
            'january',
            'february',
            'march',
            'april',
            'may',
            'june',
            'july',
            'august',
            'september',
            'october',
            'november',
            'december',
        ],
    },
    nl: {
        RELATIVE_TEXT: {
            past: {
                second: 'flus',
                seconds: 'flus',
                seconds0: 'nu',
                minute: 'een minuut geleden',
                minutes: '##rMINUTES## minuten geleden',
                minutes0: 'minder dan een minuut geleden',
                hour: 'een uur geleden',
                hours: '##rHOURS## uur geleden',
                hours0: 'minder dan een uur geleden',
                day: 'gisteren',
                days: '##rDAYS## dagen geleden',
                days0: 'vandaag',
                month: 'een maand geleden',
                months: '##rMONTHS## maanden geleden',
                months0: 'minder dan een maand geleden',
                year: 'een jaar geleden',
                years: '##rYEARS## jaaren geleden',
                years0: 'minder dan een jaar geleden',
            },
            now: {
                now: 'nu',
            },
            future: {
                second: 'in een paar seconden',
                seconds: 'in een paar seconden',
                seconds0: 'nu',
                minute: 'in een minuut',
                minutes: 'in ##rMINUTES## minuten',
                minutes0: 'in minder dan een minute',
                hour: 'in een uur',
                hours: 'in ##rHOURS## uur',
                hours0: 'in minder dan een uur',
                day: 'morgen',
                days: 'in ##rDAYS## dagen',
                days0: 'vandaag',
                month: 'in een maands',
                months: 'in maanden',
                months0: 'in minder dan een maand',
                year: 'in een',
                years: 'in ##rYEARS## Jaaren',
                years0: 'in minder dan een jaar',
            },
        },
        ABSOLUTE_TEXT: {
            date: '##aDAYS##-##aMONTH##-##aYEARS##',
            dateMW: '##aDAYS## ##aMONTHw## ##aYEARS##',
            time: '##aHOURS##.##aMINUTES## uur',
            datetime: '##aDAYS##-##aMONTH##-##aYEARS##, ##aHOURS##.##aMINUTES## uur',
            datetimeMW: '##aDAYS## ##aMONTHw## ##aYEARS##, ##aHOURS##.##aMINUTES## uur',
            at: 'om',
        },
        INTERVAL: {
            differentDays: '##DATE1##, ##TIME1## - ##DATE2##, ##TIME2##',
            sameDay: '##DATE1##, ##TIME1## - ##TIME2##',
        },
        WEEKDAYS: [
            'maandag',
            'dinsdag',
            'woensdag',
            'donderdag',
            'vrijdag',
            'zaterdag',
            'zondag',
        ],
        MONTHS: [
            'january',
            'februari',
            'maart',
            'april',
            'mei',
            'juni',
            'juli',
            'augustus',
            'september',
            'oktober',
            'november',
            'december',
        ],
    },
};

export default text;
