const text = {
    de: {
        RELATIVE_TEXT: {
            past: {
                second: 'Gerade eben',
                seconds: 'Gerade eben',
                minute: 'vor einer Minute',
                minutes: 'vor ##MINUTES## Minuten',
                hour: 'vor einer Stunde',
                hours: 'vor ##HOURS## Stunden',
                day: 'Gestern',
                days: 'vor ##DAYS## Tagen',
                month: 'vor einem Monat',
                months: 'vor ##MONTHS## Monaten',
                year: 'vor einem Jahr',
                years: 'vor ##YEARS## Jahren',
            },
            now: 'Jetzt',
            future: {
                second: 'in wenigen Sekunden',
                seconds: 'in wenigen Sekunden',
                minute: 'in einer Minute',
                minutes: 'in ##MINUTES## Minuten',
                hour: 'in einer Stunde',
                hours: 'in ##HOURS## Stunden',
                day: 'Heute',
                days: 'in ##DAYS## Tagen',
                month: 'in einem Monat',
                months: 'in ##MONTHS## Monaten',
                year: 'in einem Jahr',
                years: 'in ##YEARS## Jahren',
            },
        },
        ABSOLUTE_TEXT: '##DAYS##.##MONTHS##.##YEARS##, ##HOURS##:##MINUTES## Uhr',
        WEEKDAYS: [
            'Montag',
            'Dienstag',
            'Mittwoch',
            'Donnerstag',
            'Freitag',
            'Samstag',
            'Sonntag',
        ],
        MONTHS: [
            'Januar',
            'Februar',
            'März',
            'April',
            'Mai',
            'Juni',
            'Juli',
            'August',
            'September',
            'Oktober',
            'November',
            'Dezember',
        ],
    },
};

export default text;
