const text = {
    de: {
        RELATIVE_TEXT: {
            past: {
                second: 'Gerade eben',
                seconds: 'Gerade eben',
                seconds0: 'Jetzt',
                minute: 'vor einer Minute',
                minutes: 'vor ##rMINUTES## Minuten',
                minutes0: 'vor weniger als einer Minute',
                hour: 'vor einer Stunde',
                hours: 'vor ##rHOURS## Stunden',
                hours0: 'vor weniger als einer Stunde',
                day: 'Gestern',
                days: 'vor ##rDAYS## Tagen',
                days0: 'Heute',
                month: 'vor einem Monat',
                months: 'vor ##rMONTHS## Monaten',
                months0: 'vor weniger als einem Monat',
                year: 'vor einem Jahr',
                years: 'vor ##rYEARS## Jahren',
                years0: 'vor weniger als einem Jahr',
            },
            now: {
                now: 'Jetzt',
            },
            future: {
                second: 'in wenigen Sekunden',
                seconds: 'in wenigen Sekunden',
                seconds0: 'Jetzt',
                minute: 'in einer Minute',
                minutes: 'in ##rMINUTES## Minuten',
                minutes0: 'in weniger als einer Minute',
                hour: 'in einer Stunde',
                hours: 'in ##rHOURS## Stunden',
                hours0: 'in weniger als einer Stunde',
                day: 'Morgen',
                days: 'in ##rDAYS## Tagen',
                days0: 'Heute',
                month: 'in einem Monat',
                months: 'in ##rMONTHS## Monaten',
                months0: 'in weniger als einem Monat',
                year: 'in einem Jahr',
                years: 'in ##rYEARS## Jahren',
                years0: 'in weniger als einem Jahr',
            },
        },
        COMBINED_TEXT: {
            past: {
                second: 'Gerade eben',
                seconds: 'Gerade eben',
                minute: 'vor einer Minute',
                minutes: 'vor ##rMINUTES## Minuten',
                hour: 'vor einer Stunde',
                hours: 'vor ##rHOURS## Stunden',
                day: 'Gestern',
                days: 'vor ##rDAYS## Tagen',
                month: 'vor einem Monat',
                months: 'vor ##rMONTHS## Monaten',
                year: 'vor einem Jahr',
                years: 'vor ##rYEARS## Jahren',
            },
            now: {
                now: 'Jetzt',
            },
            future: {
                second: 'in wenigen Sekunden',
                seconds: 'in wenigen Sekunden',
                minute: 'in einer Minute',
                minutes: 'in ##rMINUTES## Minuten',
                hour: 'in einer Stunde',
                hours: 'in ##rHOURS## Stunden',
                day: 'Heute',
                days: 'in ##rDAYS## Tagen',
                month: 'in einem Monat',
                months: 'in ##rMONTHS## Monaten',
                year: 'in einem Jahr',
                years: 'in ##rYEARS## Jahren',
            },
        },
        ABSOLUTE_TEXT: {
            date: '##aDAYS##.##aMONTHS##.##aYEARS##',
            dateMW: '##aDAYS##. ##aMONTHSw## ##aYEARS##',
            time: '##aHOURS##:##aMINUTES## Uhr',
            datetime: '##aDAYS##.##aMONTHS##.##aYEARS##, ##aHOURS##:##aMINUTES## Uhr',
            datetimeMW: '##aDAYS##. ##aMONTHSw## ##aYEARS##, ##aHOURS##:##aMINUTES## Uhr',
            at: 'um',
        },
        INTERVAL: {
            differentDays: '##DATE1##, ##TIME1## - ##DATE2##, ##TIME2##',
            sameDay: '##DATE1##, ##TIME1## - ##TIME2##',
        },
        WEEKDAYS: [
            'Montag',
            'Dienstag',
            'Mittwoch',
            'Donnerstag',
            'Freitag',
            'Samstag',
            'Sonntag',
        ],
        MONTHS: [
            'Januar',
            'Februar',
            'März',
            'April',
            'Mai',
            'Juni',
            'Juli',
            'August',
            'September',
            'Oktober',
            'November',
            'Dezember',
        ],
    },
};

export default text;
