export const DYNAMIC_TOOLBAR_BADGE_MAX_VALUE = 99;
export const DYNAMIC_TOOLBAR_MIN_ITEM_WIDTH = 64;
export const DYNAMIC_TOOLBAR_SCROLL_HIDE_DELTA = 20;
export const DYNAMIC_TOOLBAR_VIEWPORT_WIDTH_RATIO = 0.8;

export const DYNAMIC_TOOLBAR_HEIGHT_PX = 85;
export const DYNAMIC_TOOLBAR_CONTENT_HEIGHT_PX = 52;
export const DYNAMIC_TOOLBAR_CONTENT_WIDTH_VW = 80;
export const DYNAMIC_TOOLBAR_CONTENT_PADDING_PX = 6;
export const DYNAMIC_TOOLBAR_OVERFLOW_TRIGGER_WIDTH_PX = 30;
export const DYNAMIC_TOOLBAR_OVERFLOW_TRIGGER_OFFSET_PX = 36;

export const DYNAMIC_TOOLBAR_BASE_CLASS = 'beta-chayns-dynamic-toolbar';
export const DYNAMIC_TOOLBAR_SPACER_BASE_CLASS = 'beta-chayns-dynamic-toolbar-spacer';
