export const MEDIA_CONTENT_IMAGE_FADE_DURATION_MS = 200;
export const MEDIA_CONTENT_IMAGE_BLUR_REMOVE_DELAY_MS = 100;
export const MEDIA_CONTENT_IMAGE_BLUR_REMOVE_DURATION_MS = 200;
export const MEDIA_CONTENT_PREVIEW_BLUR = 'blur(16px)';
export const MEDIA_CONTENT_PREVIEW_SCALE = 1.05;
